name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build site (copy root → public folder)
        run: |
          mkdir -p public
          cp -r root/code/* public/
          cp -r root/assets public/
          # Add .nojekyll so GitHub Pages doesn't try Jekyll
          touch public/.nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true   # always start fresh branch
          enable_jekyll: false # hard-disable Jekyll
